---
title: "Statistics with R"
subtitle: "Introduction to R for Actuarial Students"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---

* Introduction to R for Actuarial Students

* CS1B Curriculum

* Introduction to R programming
* Fundamentals of Statistical Analysis
* Probability Distributions

* Question 3

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)

#Higher Certificate, Paper III, 2002. Question 5

```

```{css, echo=FALSE}
pre {
  background: #ADD8E6;
  max-width: 100%;
  overflow-x: scroll;
}
```





5. Data were collected from the Financial Times of 11 October 2001 on the dividend yields of 36 Bank shares (Banks), 46 Electronic and Electrical Equipment company shares (E&EEq) and 88 Support Services company shares (SS).  (Support Services companies provide services such as catering and security to manufacturing and other companies.)  These observations were read into a computer using the Minitab package and arranged in ascending order as shown in the edited output on this page and the next. 

---
 Note that the command DESCRIBE is used to obtain the mean, median, quartiles, etc, of the three sets of observations as shown, and the commands DOTPLOT and STEM-AND-LEAF generate appropriate diagrams. 
 (i) Draw boxplots of each of the three sets of observations, indicating any outliers. (6) 
 
2.  Explain how stem and leaf diagrams display the observations, and how they relate to the dotplots.(4) 
 
3.  Write a report on the patterns of the three sets of yields, based on the output generated by the DESCRIBE command, your boxplots, and the computer-generated dotplots and stem and leaf diagrams.(10) 
 

\begin{verbatim} 
MTB > PRINT 'Banks' 
 0.00.70.80.91.02.12.12.32.42.5 2.52.72.72.82.82.93.03.03.03.0 3.13.13.13.73.83.84.14.14.14.2 4.34.44.54.54.75.1 
 MTB > PRINT 'E&EEq' 
 0.00.00.00.00.00.00.00.00.00.0 0.00.41.31.52.02.02.12.12.42.6 2.62.83.23.33.43.53.53.73.94.4 4.84.95.05.15.25.76.97.37.67.8 7.98.39.014.615.215.6 
 MTB > PRINT 'SS' 
 0.00.00.00.00.00.00.00.00.00.0 0.00.00.00.00.00.00.00.00.00.0 0.10.30.40.50.90.91.01.01.01.2 1.31.31.31.31.41.41.51.61.71.8 1.81.92.02.22.22.32.52.52.62.6 2.62.72.82.82.93.03.53.63.73.8 3.94.24.44.54.64.74.85.25.35.4 5.55.55.65.75.75.96.06.26.36.4 8.38.38.49.09.810.110.711.9 

---

MTB > DESCRIBE 'Banks' 'E&EEq' 'SS' 
 Variable NMean MedianStDevSE Mean Banks36  2.994  3.0001.232  0.205 E&EEq46  3.948  3.2503.982  0.587 SS  88  2.934  2.2002.909  0.310 
 VariableMinimumMaximum Q1 Q3 Banks0.000  5.100  2.425  4.100 E&EEq0.000 15.600  0.300  5.325 SS0.000 11.900  0.325  4.775 

---

MTB > DotPlot 'Banks'-'SS'; SUBC>Same.::. .::::.  . .::::: .:::..  +---------+---------+---------+---------+---------+-------Banks  .  :  :  :  :  : . ...  :.  .. :.: ::. .:: ....: . .  . ..  +---------+---------+---------+---------+---------+-------E&EEq  .  :  :  :  :  :  :  :  :  ..:  :  ::::..:  .  .  :. .  .  ::.:::::::: ::.::.::::  : .  .. ..  +---------+---------+---------+---------+---------+-------SS  0.03.06.09.0  12.0  15.0 
 MTB > Stem-and-Leaf 'Banks'.N  = 36Leaf Unit = 0.10 
 10 0 40 789 51 0 51  92 1134162 5577889(7)3 0000111133 788104 111234 44 557 15 1 
 MTB > Stem-and-Leaf  'E&EEq'. N  = 46Leaf Unit = 0.10 
120 000000000004141 35222 00114668(7)3 2345579174 489145 0127106 9 97 3689 58 3 49 0 310  311  312  313  314 6 215 26 
 MTB > Stem-and-Leaf  'SS'. N  = 88Leaf Unit = 0.10 
260 00000000000000000000134599421 0002333344567889(13)2 0223556667889333 056789274 245678215 234556779126 0234 87  88 334 59 08 310 17 111 9 

---

*Boxplots require median, quartiles, minimum and maximum values. As each
set of data has been arranged in increasing order of size, it is easy to check whether
any outliers have been included when making these calculations.
For Banks, the listing shows no outliers. Since N = 36, the median M is between the
18th and 19th observations, both of which are 3.0. Q1 is between the 9th and 10th,
which are 2.4 and 2.5. The program calculates 2.425; 2.45 is also acceptable. Q3 is
found in a similar way.

---

For E&EEq there are three obvious outliers. N = 46, so M is between the 23rd and
24th observations, at 3.25. Clearly the full set of data have been used in the program's
calculation (not the N = 43 when outliers are omitted). Q1, Q3 are 0.3, 5.325, or near
to these depending on the method of calculation.
The * points are outliers, and the upper whisker does not include them. [Since we use
median and quartiles, not mean and standard deviation, the difference between values
with and without outliers would not be great.]
For SS, there may be one outlier at 11.9 (although there is also considerable skewness
at the upper end). M = 2.2, Q1 = 0.325, Q3 = 4.775.
[Note. The plots drawn above might not appear exactly correct, due to screen and/or printer
resolution.]
Continued on next page
0 1 2 3 4 5
x
6
x
0 3 6 9 12 15 18
* **
x
0 3 6 9 12
*
*The column of numbers 001122… is the "stem", which is the number before
the decimal point. To the right of this, listed in increasing order, are the "leaves",
which are the decimal parts; those with decimal parts 0 – 4 are listed on one row, and
5 – 9 on the next row below; for example,
0 0
0 789
shows that the first four data in
'Banks' were 0.0 0.7 0.8 0.9.

---

Frequencies are cumulated, row by row, from each end, so that they meet in the
middle, where the bracketed number, e.g. (7) for Banks, shows the actual frequency in
the interval containing the median.
The dotplots show where each observation is located on the scale of measurement,
with one dot for each item. (On the scales used here, spacing forces some adjacent
numbers to come together.)
*Banks: There are 4 very low figures, 1% or less; apart from these, there is a
reasonably symmetrical pattern with 3% as its approximate centre. The spread of this
set of data is not great; there are no upper outliers and the range of the 32 items
excluding the 4 low ones is from 2.1 to 5.1.
E&EEq: The DESCRIBE program results are rather distorted by the three very large
observations, which are clearly outliers, and the general skewness of the whole
pattern. There is a substantial number of zeros. An "exponential decay" pattern (an
exponential distribution) might explain all but the last three.
SS: This is rather similar to E&EEq, having several zeros and an exponential pattern.
However, this pattern gradually tails off and does not have outliers far above their
neighbours – it is probably wise to treat 11.9 as an outlier, although it would fit an
exponential distribution.

---

General: Stem and leaf diagrams seem to give the interpretation more easily than
dotplots (at least with the program used) but the numerical descriptive summaries
seem less satisfactory than either of these graphical methods. The question of a subgroup
of zeros arises in two of the data sets.
\end{enumerate}

