---
title: "Statistics with R"
subtitle: "Probability Distributions"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---

```{r echo=FALSE}
library(magrittr)
library(knitr)
```

In a factory manufacturing electronic components, there are four machine operators 
and five machines producing similar items. The quality of the components having 
been variable, an experiment was conducted to determine whether the variability was 
caused by differences between machines, differences between operators or both. The 
production was observed for each shift, with each operator using each of the five 
machines for a whole shift. The quality of the components produced during any shift 
was assessed by quality control inspectors on a scale of 0 to 100, with 100 
corresponding to perfect quality and 0 to useless material. 


---

The values of the quality 
scores were as given in the following table. 
Machine
A B C D E 
Operator 1 56 92 53 93 68 
Operator 2 64 83 55 95 62 
Operator 3 62 80 56 96 62 Operator 
Operator 4 51 78 44 88 69 
---
Sums for the five machines are 233, 333, 208, 372, 261; sums for the four operators 
are 362, 359, 356, 330; the sum of squares of the 20 values is 104127. 


(i) Write down a linear model which could be used as the basis for an analysis of 
a set of data such as that shown above. Explain clearly what each term in the 
model represents, and state any assumptions required for the analysis to be 
valid. 
---
2.  Carry out an appropriate analysis of variance, and test for differences between 
operators and between machines. 

---

3.  Explain briefly how you might attempt to check whether the assumptions 
required for an analysis of variance are satisfied.

---

%%-- HKSS HC2 - 2007 - Question 3
%%-- https://hkss.org.hk/index.php/prof/exam/doc?highlight=WyJleGFtcyIsImV4YW0iXQ==

