censReg Censored Regression (Tobit) Model

#### Description
Fitting a model with a censored dependent variable.

#### Usage
<pre><code>

censReg( formula, left = 0, right = Inf, data = sys.frame( sys.parent()),
start = NULL, nGHQ = 8, logLikOnly = FALSE, ... )
## S3 method for class 'censReg'
print( x, logSigma = TRUE, digits = 4, ... )
</code></pre>

#### Arguments
formula an object of class "formula": a symbolic description of the model to be fitted.
left left limit for the censored dependent variable; if set to -Inf, the dependent variable is assumed to be not left-censored; defaults to zero (classical Tobit model).
right right limit for the censored dependent variable; if set to Inf, the dependent variable is assumed to be not right-censored; defaults to Inf (classical Tobit model).
data an optional data frame. If argument data is of class "pdata.frame", a panelmodel is estimated.
start an optional vector of initial parameters for the ML estimation (intercept, slope parameters, logarithm of the standard deviation of the individual effects (only for random-effects panel data models), and logarithm of the standard deviation
of the general disturbance term); if start is not specified, initial values are taken from an OLS estimation or (uncensored) random-effects panel data estimation.
nGHQ number of points used in the Gauss-Hermite quadrature, which is used to compute the log-likelihood value in case of the random effects model for panel data.
logLikOnly logical. If TRUE, the model is not estimated but the log-likelihood contributions of all observations/individuals and the corresponding gradients calculated at the parameters specified by argument start are returned.
x object of class censReg (returned by censReg).
logSigma logical value indicating whether the variance(s) of the model should be printed
logarithmized (see coef.censReg).
digits positive integer specifiying the minimum number of significant digits to be printed
(see print.default).
... additional arguments for censReg are passed to maxLik; additional arguments
for print.censReg are currently ignored.

#### Details
The model is estimated by Maximum Likelihood (ML) assuming a Gaussian (normal) distribution of the error term. The maximization of the likelihood function is done by function maxLik of the maxLik package. An additional argument method can be used to specify the optimization method used by maxLik, e.g.\ "Newton-Raphson", "BHHH", "BFGS", "SANN" (for simulated annealing), or
"NM" (for Nelder-Mead).


#### Examples
```{r}
## Kleiber & Zeileis ( 2008 ), page 142
data( "Affairs", package = "AER" )
estResult <- censReg( affairs ~ age + yearsmarried + religiousness +
occupation + rating, data = Affairs )
print( estResult )
## Kleiber & Zeileis ( 2008 ), page 143
estResultBoth <- censReg( affairs ~ age + yearsmarried + religiousness +
occupation + rating, data = Affairs, right = 4 )
print( estResultBoth )

```
#### Value
If argument logLikOnly is FALSE (default), censReg returns an object of class "censReg" inheriting from class "maxLik". The returned object contains the same components as objects returned by maxLik and additionally the following components:
call the matched call.
terms the model terms.
nObs a vector containing 4 integer values: the total number of observations, the number
of left-censored observations, the number of uncensored observations, and
the number of right-censored observations.
df.residual degrees of freedom of the residuals.
start vector of starting values.
left left limit of the censored dependent variable.
right right limit of the censored dependent variable.
xMean vector of mean values of the explanatory variables.
In contrast, if argument logLikOnly is TRUE, censReg returns a vector of the log-likelihood contributions
of all observations/individuals. This vector has an attribute "gradient", which is a matrix
containing the gradients of the log-likelihood contributions with respect to the parameters.
Note
When the censored regression model is estimated, the log-likelihood function is maximized with
respect to the coefficients and the logarithm(s) of the variance(s).
Author(s)
Arne Henningsen
References
Greene, W.H. (2008): Econometric Analysis, Sixth Edition, Prentice Hall, p. 871-875.
Kleiber, C. and Zeileis, A. (2008): Applied Econometrics with R, Springer, p. 141-143.
Tobin, J. (1958): Estimation of Relationships for Limited Dependent Variables. Econometrica 26,
p. 24-36.
See Also
summary.censReg, coef.censReg, tobit, selection
