coef.summary.censReg Coefficients of Censored Regression Models and their Statistical Properties
Description
This function returns the estimated coefficients of censored regression models as well as their standard
errors, z-values, and P-values.
<
#### Usage
<pre><code>

## S3 method for class 'summary.censReg'
coef( object, logSigma = TRUE, ... )
Arguments
object object of class "summary.censReg" (returned by summary.censReg).
logSigma logical value indicating whether the variance(s) of the model should be returned
logarithmized.
... currently not used.
6 margEff.censReg
Value
coef.summary.censReg returns an matrix, where each row corresponds to one coefficient and the
4 rows contain the estimated coefficients, their standard errors, z-values, and P-values.
Author(s)
Arne Henningsen
See Also
censReg, summary.censReg and coef.censReg
<
#### Examples

## Kleiber & Zeileis ( 2008 ), page 142
data( "Affairs", package = "AER" )
estResult <- censReg( affairs ~ age + yearsmarried + religiousness +
occupation + rating, data = Affairs )
coef( summary( estResult ) )
