coef.censReg Coefficients, their Covariances, and Log-Likelihood Values of Censored Regression Models

#### Description
These functions extract the coefficient vectors, the corresponding covariance matrices, and loglikelihood
values from censored regression models.

#### Usage
<pre><code>

## S3 method for class 'censReg'
coef( object, logSigma = TRUE, ... )
## S3 method for class 'censReg'
vcov( object, logSigma = TRUE, ... )
## S3 method for class 'censReg'
logLik( object, ... )
</code></pre>

#### Arguments
object object of class "censReg" (returned by censReg).
logSigma logical value indicating whether the variance(s) of the model should be returned
logarithmized.
... currently not used.


#### Examples
```{r}
## Kleiber & Zeileis ( 2008 ), page 142
data( "Affairs", package = "AER" )
estResult <- censReg( affairs ~ age + yearsmarried + religiousness +
occupation + rating, data = Affairs )
coef( estResult )
coef( estResult, logSigma = FALSE )
vcov( estResult )
vcov( estResult, logSigma = FALSE )
logLik( estResult )
```
#### Value
* coef.censReg returns a vector of the estimated coefficients.
* vcov.censReg returns the covariance matrix of the estimated coefficients.
* logLik.censReg returns an object of class "logLik". This object is the log-likelihood value of the estimated model and has an attribute "df" that gives the degrees of freedom, i.e. the number of estimated parameters.

#### Note
When the censored regression model is estimated, the log-likelihood function is maximized with respect to the coefficients and the logarithm(s) of the variance(s). Hence, if argument logSigma is FALSE, the variance(s) of the model is/are calculated by applying the exponential function to the estimated logarithmized variance(s) and the covariance matrix of all parameters is calculated by the
Delta method.

#### Author(s)
Arne Henningsen

#### See Also
censReg, summary.censReg, and coef.summary.censReg
