---
title: "Statistics with R"
subtitle: "R for Actuarial Students"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---

```{r}

#library(xaringan)
```

 

Time ( t ) Water uptake ( y )
w ( = t/y )
2 0.69 2.883 4 1.50 2.664 6 1.43 4.180 8 1.64 4.866 10 2.01 4.952 12 1.96 6.122 14 2.28 6.133 16 2.10 7.620 18 2.02 8.887 20 2.33 8.578 22 2.32 9.454 24 2.42 9.936


Theory suggests that water uptake is expected to be related to time by the hyperbolic law:
y
ct dt
=
+
.


* 
(i) Show that if the hyperbolic law does hold then there is a linear relationship between the transformed variable  w  and  t, where w =  t/y.
* 
(ii) Plot the values of  w  (which are given in the third column of the table), against t.
* 
(iii) Use the method of least squares to determine estimates \alpha\beta  and of the parameters \alpha\beta  and of the best fitting straight line: wt =+ \alpha\beta  .
 [Note that 39073 .76=∑ w and wt ∑ = 119046022. .]


---



---



%---------------------------------%
4.(i) $y = \frac{ct}{d+t} or $yd+yt = ct$ or $d+t = c\omega$ .

This can be written as $\omega  = \alpha+\beta t$, where $\alpha = \frac{d}{c}; $\beta = \frac{1}{c}$.

(ii)
(iii)The fitted line is $\omega −\bar{\omega}  = \hat{\beta} (t−\bar{t}) where

\begin{eqnarray*}
\hat{ \beta}  &=& P(\omega − \bar{\omega} )(t−\bar{t})P (t−\bar{t})2 \\
&=& P\omega t−P\omega Pt/n Pt2−(Pt)2/n\\
&=& 1190.46022−156 \times 76.39073/12 2600−1562/12 \\
&=& 197.38073 572 = 0.34507 .
13
\end{eqnarray*}


Hence \hat{\alpha} = 76.39073 12 − \hat{ \beta} ×13 = 1.87997.


 
---

* (iv) Hence, obtain estimates $\hat{ c}d$ and of the parameters c and d in the hyperbolic law.
* 
(v) What value of water uptake does the fitted hyperbolic law predict at 16 hours?
* 
(vi) Indicate briefly any technical difficulties which arise in obtaining standard errors of $\hat{ c}$ and $\hat{ d}$ when you are given the standard errors of $\alpha$ and $\beta$ .



---

* (iv) $ \displaystyle{  \hat{ c} = \frac{1} { \hat{ \beta} }  = 0.898 }$ and $\hat{ d} = ˆ c \hat{\alpha} = 5.448$.
* (v)Using $ \displaystyle{ y = \frac{2.898t}{5.448+t} }$, when $t=16$, gives $y=2.16$.
* 
(vi)The parameters $\hat{ c}$ and $\hat{ d}$ are non-linear functions of $\hat{\alpha}$ and $\hat{\beta}$ so there are no simple formula for the relations between standard errors.



