---
title: "Statistics with R"
subtitle: "R for Actuarial Students"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---

```{r}

#library(xaringan)
```


3. The infant mortality rate per 1000 live births and the percentage adult female literacy rate for a sample of countries are given in the table below. 
 
 
\begin{tabular}{|c|c|c|}
Country &  Infant mortality rate  & Percentage adult \\
        & per 1000 live births    & female literacy rate \\ 
        A	&	160	&	71	
B	&	116	&	79	
C	&	94	&	47	
D	&	87	&	70	
E	&	84	&	71	
F	&	83	&	84	
G	&	83	&	80	
H	&	60	&	88	
J	&	50	&	86	
K	&	43	&	90	
L	&	35	&	95	
M	&	31	&	88	
N	&	27	&	93	
P	&	25	&	96	
R	&	22	&	93	
\end{tabular}




    * Sum 1000 1231 
    * Sum of squares 88268 103411 
    * Sum of products 77068 


 
(i) Make a scatter plot of these data using the vertical axis for infant mortality rate. (4) 
 
(ii) Use the additional information contained in the table to fit a linear relation which could be used to predict infant mortality rate from adult female literacy rate. (4) 
 

 


%%%%

* (i) (i)(iii)(v) See next sheet.
* n = 15; ¯y = 1000=15 = 66:67; ¯x = 1231=15 = 82:07;
P
y2 = 88268;
P
xy =
77068;
P
x2 = 103411 Therefore \hat{y} = 378:81 ¡ 3:714x.
ˆb
= (1706:5 ¡
12310:00
15
) ¥ (103411 ¡
1231
15
) = ¡
4987:67
2386:93
= ¡2:094
ˆa = 66:667 + 2:094 £ 82:007 = 238:51 Therefore $\hat{y} = 238:51 - 2:094x$. Line A:
* $\hat{y} = 378:81 ¡ 3:714x$ Line B:

\newpage


 
 
(iii) Plot the fitted line on the scatter plot. 
(2) 
 
(iv) Modify your calculations to exclude country C from the fitted relation. 
(4) 

---



 
 
(v) Plot the new fitted line on the scatter plot. 
(2) 
 
(vi) What do you conclude about the effect of country C?  What would be your recommendations about which equation should be used to predict infant mortality rate? (4) 


---
* Country C is out of step with the others, and is very influential in determining the fitted
line. In fact neither line fits the lower literacy rate values at all well, although line B does
rather better than A for the upper values.The variability in y as x decreases suggests
that a linear regression assuming constant variance is not lively to do well; a weighted
regression might be considered if suitable data is variable.



