---
title: "Statistics with R"
subtitle: "R for Actuarial Students"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---

```{r}

#library(xaringan)
```

 
 
4. Silicon chip manufacture involves a complex process in which layers are deposited on a wafer of silicon by vapour deposition at high temperatures. An electronics engineering team investigated the effect of deposition time and deposition temperature on the thickness of a particular layer. They particularly wanted to find out whether either factor alone could be used to control the thickness of the layer. They used two settings of deposition time  (Low and High relative to currently used time) and two temperatures (1210°C and 1240°C). Measurements of the thickness of the layer were made on each of five silicon wafers produced under each set of conditions. The measurements are given in the table below.
Thickness of layer (Ëm)
Deposition Time High Low
Deposition
1210 14.90,  14.69,  14.52, 15.14,  14.63.
13.78,  14.18,  13.58, 13.58,  13.81.
Temperature
1240 14.49,  14.33,  13.94, 14.31,  14.18.
14.27,  14.37,  14.16, 14.03,  14.20.
The sum of the 20 measurements is 285.09 and the corresponding sum of squares is 4067.00.

---

(i) Perform an analysis of variance, including tests for the effects of time and temperature and the interaction between time and temperature.



---


 
 
(ii) Produce a diagram of means and their standard errors which makes clear the nature of any interaction that there may be between time and temperature.
(iii) Write a short report (4 or 5 informative sentences) which explains the findings of your analysis in non-technical language for the team who carried out the investigation.

---

4. 2 £ 2 factorial experiment in 5 replicates, completely randomized.
TOTALS.
Time: H L
1210 73:88 68:93 : 142:81
1240 71:25 71:03 : 142:28
145:13 139:96 285:09

*  Correction term G2=N = 285:092=20 = 4063:8154.
S.S. for Times = 1
10(145:132 + 139:962) \;-\;G2
N = 1:33645
S.S. for Temperatures = 1
10(142:812 + 142:282) \;-\;G2
N = 0:01405
S.S. for all “treatments” = 1
5(73:882+68:932+71:252+71:032)¡G2
N = 2:46914.
* Corrected total S.S. = 4067:00 \;-\;4063:8154 = 3:1846.

\begin{verbatim}
Analysis of Variance.
D:F: S:S: M:S:
Temperatures 1 0:01405 0:0141
Times 1 1:33645 1:3365
Interaction 1 1:11864 1:1186 F(1;16) = 25:03¤¤¤
3 2:46914
Residual 16 0:71546 0:0447 = s2:
TOTAL 19 3:18460    
---

Since there is a very strong interaction of time with temperature, main effects
should not be quoted.
*  Means are:
Time: H L
Temperature 1210 14:78 14:79
1240 14:25 14:21

    * A graph shows the results clearly:
* The standard error of a single mean is
p
s2=5 = 0:095. * Hence at 12400 C,
time has no effect, while at 12100 C time H gives a thicker layer.


*  Report should make the point that neither time nor temperature alone
determines the thickness of the layer; also for a thicker layer we should
use the lower temperature and longer time, while the lower temperature
and shorter time gives a relatively thin layer. At the higher temperature,
with either time, the thickness of the layer is between these other two, and
apparently not affected by time.


