---
title: "Statistics with R"
subtitle: "R for Actuarial Students"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---

```{r}

#library(xaringan)
```

 
2. An investigation was carried out into the levels of chlordanes in wild polar bears. The levels of chlordanes in 25 sub-adult polar bears, 23 adult females and 20 adult males are given in the table below, together with the corresponding transformed values obtained by taking logarithms to the base 10 to two places of decimals. 

The bears were those which the investigators were able to locate and anaesthetise for long enough to collect tissue samples which could be assayed for chlordanes and other organo-chlorine compounds. It is safe to assume that the bears located were a random sample of those in the areas covered by the investigation.

---

Chlordane levels in tissue (nano-grams/gram) Sub-adults Adult females Adult males 
Original Data Log transformed Original data Log transformed Original Data Log transformed 
1081 3.03 813 2.91 475 2.68 1188 3.07 881 2.95 610 2.79 
1449 3.16 1170 3.07 675 2.83 1657 3.22 1219 3.09 788 2.90 1805 3.26 
1350 3.13 916 2.96 1846 3.27 1409 3.15 1089 3.04 1960 3.29 1521 3.18 
1321 3.12 2069 3.32 1932 3.29 1330 3.12 2089 3.32 2049 3.31 1357 3.13 
2272 3.36 2201 3.34 1584 3.20 2664 3.43 2771 3.44 1802 3.26 2971 3.47 
2859 3.46 1877 3.27 3329 3.52 2985 3.47 2045 3.31 3900 3.59 3094 3.49 
2282 3.36 4349 3.64 3855 3.59 2520 3.40 4539 3.66 3876 3.59 2888 3.46 
4746 3.68 4142 3.62 3060 3.49 4819 3.68 4397 3.64 4994 3.70 5597 3.75 
4832 3.68 6238 3.80 5607 3.75 5473 3.74 6241 3.80 6013 3.78 5825 3.77 
6291 3.80 6414 3.81 7908 3.90 7511 3.88 8219 3.91 8505 3.93

Note that the observed values have been ordered.

---

### Exercise 1
(i) Make box-plots of the raw data and also of the logarithms to the base 10 of the observed chlordane levels.


### Exercise 2
(ii) Describe how the shapes of the distributions of the raw data and the log transformed data differ.



---




---




2.For sub-adults, nS = 15; for females, nF = 23; for males, nM = 20. Medians and quartiles are:
MS = 3329(13M:
item); MF = 2859(12M:
item); MM = 1693(averrage of 10M:
and 11M:
items):
Transformed: MS = 3:52; MF = 3:46; MM = 3:23.
Lower quartiles: qS = 1
2 (1846+1960) = 1903 or 3:28; qF = 1409 or 3:15; qM = 1
2 (916+1089) =
1002:5 or 3:00.
Upper quartiles: QS = 5602 or 3:75; QF = 4397 or 3:64; QM = 1
2 (2520 + 2888) = 2704 or 3:43.
(i) (ii)

---

    * These three distributions are all distinctly skew to the right.
* The diagrams for log10(data) show much more symmetry, and much more constant variability.
* The basic assumptions for analysis of variance are therefore much more reasonable in these units.

5


---
### Exercise 3

* There is evidence from studies of other animals that chlordanes tend to accumulate most in fatty tissue and can be passed from female mammals to their offspring through the mother's milk during the nursing period. Females tend to have considerably more fatty tissue than males. 

* The investigators are interested in comparing average levels of chlordanes between sub-adults and male and female adults. A partially completed analysis of variance table for the log transformed data is given below. 

* Complete this analysis and explain in non-technical terms what can be concluded from the analysis.

---

Analysis of Variance of Chlordane levels in polar bears.
Source of Variation
Sum of squares
Degrees of freedom
Mean square
Variance ratio
Between groups 0.8930 Residual Total 6.3774 67



---
(iii)Analysis of Variance
11
\begin{verbatim}
SOURCE DF SUM OF SQUARES MEAN SQUARE
Between groups 2 0:8930 0:4465
Residual 65 5:4844 0:0844
Total 67 6:3774
F(2;65) = 5:29¤¤
---
There are substantial differences between the three groups of animals.

---

 
 
(iv) Carry out a follow up analysis by calculating individual 95 per cent confidence intervals for the three groups, using the pooled estimate of error variance in determining the standard errors of the group means. 

Explain what this analysis reveals.
(v) Back transform the group means and the 95 percent confidence intervals to the original scale.

---

(iv)Using the log data, we may compare the rations of chlordane levels in the different groups.
The 95z% limits in log10 units are:
Sub adults : 3:51 § 2:00
q
0:0844
25 or 3:51 § 0:12; i:e: 3:39 to 3:63
Females : 3:42 § 2:00
q
0:0844
23 or 3:42 § 0:12; i:e: 3:30 to 3:54
Males : 3:23 § 2:00
q
0:0844
20 or 3:23 § 0:13; i:e: 3:10 to 3:36

---

    * To answer the questions the investigators had in mind, the sub-adults could be compared
with adults of each sex in significant tests. 
* The confidence intervals in this particular experiment
indicate what the results of these comparisons would be: sub-adults and adult females show no
real difference(intervals overlap considerably) but adult males and sub-adults do show significant
difference(no overlap of intervals).

---

* [NOTE that males and females differ at the 5% significance level; but it not clear that we need
to make this comparison, and the confidence intervals alone do not tell us this. ]
* (v)Anti-logs to base 10 give the intervals as follows:
Males 1260 to 2290; Females 2000 to 3470;
Sub-adults 2450 to 4270 (to nearest 10 ng/g).




