---
title: "Statistics with R"
subtitle: "R for Actuarial Students"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---

```{r}

#library(xaringan)
```






---

Higher Certificate, Paper III, 2004.  Question 6 



Some measurements of the volume v (cc) of a casting at seven different temperatures t (in degrees Celsius) of the casting are shown below.  
 
Temperature 18 19 20 21 22 23 24 Volume 10.10 10.80 11.45 12.18 12.80 13.35 15.90 
        Σt2 = 3115 Σv2 = 1092.9774 Σtv = 1842.03 
 
Two linear regressions have been estimated, one using all seven pairs of measurements, and one omitting the last measurement listed (temperature = 24°C).  Edited results are shown below;  some quantities relating to the first regression have been omitted deliberately. 


---

Regression Analysis: volume versus temperature – all measurements 

The regression equation is volume = ** + ** temperature 
 
Predictor        Coef     SE Coef        T        P Constant          **      2.386      -2.31    0.069 temperature       **      0.1131      7.53    0.001 
 
S = 0.5986      R-Sq = **%     

---

Regression Analysis: volume versus temperature – omitting measurement at 240C 
\begin{verbatim}
The regression equation is volume = -1.68 + 0.657 temperature 
 
Predictor        Coef       SE Coef         T        P Constant        -1.6797     0.2803      -5.99    0.004 temperature      0.65657    0.01362     48.19    0.000 
 
S = 0.05700     R-Sq = 99.8%      

---  
 
(i) Plot the data and comment. 

 
(ii) Calculate the missing estimated coefficients in the first regression, and find the coefficient of determination R2. (5) 
 
(iii) Which regression do you think is better, and why? 

---
 (iv) For your preferred regression, interpret its estimated coefficients and its R2.  Explain the meanings of the values of "SE Coef", "T" and "P" given above for it.  Why are these values useful? (7) 
 
---
 
(i) 
 
Without the last point, there is an almost linear relation (perhaps a very slight flattening off?).  The last point is considerably different (perhaps the measurement as recorded is an error for 13.90?). 
 
 
(ii) The coefficients can be calculated using the usual linear regression formulae, but from the edited results each may be calculated directly as "T × SE Coef".  Thus they are –5.51 and 0.852 respectively, so the fitted line is 
 "Volume  =  –5.51  +  0.852 × Temperature". 
 R2 can be calculated as Sxy2/SxxSyy in the usual notation, i.e. here 
 
()
2
2
22 147 86.581842.03 23.85 7 0.919 28 22.1065147 86.58 3115 1092.9774 77 ×  −  == ×    −−       (or 91.9%). 
 
---

(iii) The regression omitting the last point gives a much better fit to the remaining points.  This is reflected in the smaller residual mean square ((0.05700)2 instead of (0.5986)2) and hence the smaller standard errors of the coefficients, both of which give highly significant t statistics.  R2 is also greater for this regression.  If, however, the last point is considered to be genuine and important, it is obviously not taken into account at all by the regression omitting it.  

---

The first regression does include it, but arguably a more complicated model than simple linear regression should be used anyway. 
 
18 21 24 
10
13
16
Volume v (cc)
Temperature t (degrees Celsius) 

---
 
(iv) As given by the second regression, volume increases by 0.657 cc for each 1 degree increase in temperature.  
 
* The line, if projected back, would have v = –1.68 when t = 0 (this is of course absurd;  obviously the linear regression would not hold that far outside the range of the available data). 
* $R^2$ is the proportion (usually given as a percentage, as in the edited results) of the total variation in the data that is explained by the regression relation. 

* "SE Coef" is the standard error of each regression coefficient.  "T" is the value of each coefficient divided by its standard error (i.e. it is the value of the t test statistic for testing the hypothesis that the true value of the coefficient is zero).  "P" is the probability of obtaining the calculated value of T or a more extreme value, on the null hypothesis that the true value of the coefficient is zero. 
 
---

* These values indicate the precision with which the line is fitted and allow the null hypothesis for each coefficient to be tested.  Since P < 0.05 for each coefficient, we would reject each null hypothesis at the 5\% level (indeed, the results are very highly significant, beyond the 5\% level) and conclude that temperature does appear to (help to) explain volume. 


 
* In calculating P, a Normal distribution of the residual terms in the usual linear regression model is assumed. 
  
 
