---
title: "Statistics with R"
subtitle: "R for Actuarial Students"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---

```{r}

#library(xaringan)
```


1. The following data are from Altman (1991), Practical Statistics for Medical Research, and represent measurements of 
foetal head circumference (cm) made by four observers.  

Each observer made three independent measurements of the head circumference for each foetus. 
 
 
Foetus Observer       1 2 3 4       

14.3 13.6 13.9 13.8 1 14.0 13.6 13.7 14.7  14.8 13.8 13.8 13.9       
19.7 19.8 19.5 19.8 2 19.9 19.3 19.8 19.6  19.8 19.8 19.5 19.8       
13.0 12.4 12.8 13.0 3 12.6 12.8 12.7 12.9  12.9 12.5 12.5 13.8 
 
---
 
The analysis of variance (ANOVA) table is 

\begin{tabular}{ccccc} 
Source	&	DF	&	SS	&	MS	&	F	\\
Foetuses	&	2	&	$\ldots$	&	$\ldots$	&	$\ldots$	\\
Observers	&	$\ldots$	&	$\ldots$	&	$\ldots$	&	$\ldots$	\\
Foetuses × Observers	&	$\ldots$	&	0.562	&		&		\\
Error	&	$\ldots$	&	$\ldots$	&	0.0767	&		\\
Total	&	35	&	327.61	&		&		\\  
\end{tabular}
 
 
(i) Complete the ANOVA table and use it to assess what evidence the experiment provides regarding the main effects 
and the interaction between the factors foetus and observer. (10) 
 
(ii) Draw a simple diagram using the twelve mean values which illustrates the effects of foetus, observer and their interaction. (5) 
 
(iii) Summarise your conclusions in non-technical language which the experimenter would understand. (5) 
 
---
 
*  The main effect terms need to be calculated; the remaining information then follows
using what is given, once the degrees of freedom have been completed.
TOTALS: Foetus 1 167.9 Observer 1 141.0 N = 36
2 236.3 2 137.6 Grand total G = 558.1
3 153.9 3 138.2
4 141.3 G 2/N = 8652.1003
Corrected ( ) 2
2 2 2
FOETUS
SS 1 167.9 236.3 153.9 324.0089
12
G
N
= + + − = .
Corrected ( )2
2 2 2 2
OBSERVER
SS 1 141.0 137.6 138.2 141.3 1.1986
9
G
N
= + + + − = .


---

Source df Sum of Squares Mean Square F value
Foetuses (F) 2 324.009 162.004 2112 (very highly sig)
Observers (O) 3 1.199 0.400 5.22 (highly sig)
Interaction (O × F) 6 0.562 0.094 1.22 (not sig).
Error (Residual) 24 1.840 0.0767
Total 35 327.610

The interaction term is not significant. Each main effect is highly significant.
*  The means are:
Observer
1 2 3 4
1 14.37 13.67 13.80 14.13
Foetus 2 19.80 19.63 19.60 19.73
3 12.83 12.57 12.67 13.23

---

The diagram shows the very large difference between foetuses, the small difference between
observers by comparison (even though it is significant at 1%) and the negligible interaction
(as the three lines are roughly parallel).
12
13
14
15
16
17
18
19
20
1 2 3 4
OBSERVER
Circumference
Foetus 2
Foetus 1
Foetus 3

---

*  The four observers did not produce exactly the same results on each foetus, but the
differences among observers were small by comparison with those between foetuses. There
was no evidence that different observers were measuring the different foetuses inconsistently
(i.e. there was no "interaction" between O and F).




