---
title: "Statistics with R"
subtitle: "R for Actuarial Students"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---

```{r}

#library(xaringan)
```

 
 
6. A drug intended to reduce blood pressure was tested in the early stages of a clinical trial on 15 patients who had high blood pressure.  For each patient both the systolic blood pressure and the diastolic blood pressure were measured before they were given the drug.  They were then given the drug and both systolic and diastolic blood pressure were measured one hour later.  Systolic blood pressure is measured as the heart contracts to pump blood around the body.  Diastolic blood pressure is measured as the heart relaxes to allow blood to flow into it before the next contraction.  Systolic blood pressure is always higher than diastolic blood pressure and the two are positively correlated. 
 
---

 The measured values and the differences between the values before and after taking the drug are given below. 
 
Patient number 
Systolic  b.p.  before 
Systolic  b.p.  after 
Systolic  b.p.  difference 
Diastolic  b.p.  before 
Diastolic  b.p.  after 
Diastolic  b.p. difference 
1 210 201 9 130 125 5 2 169 165 4 122 121 1 3 187 166 21 124 121 3 4 160 157 3 104 106 -2 5 167 147 20 112 101 11 6 176 145 31 101 85 16 7 185 168 17 121 98 23 8 206 180 26 124 105 19 9 173 147 26 115 103 12 10 146 136 10 102 98 4 11 174 151 23 98 90 8 12 201 168 33 119 98 21 13 198 179 19 106 110 -4 14 148 129 19 107 103 4 15 154 131 23 100 82 18 Sum 2654 2370 284 1685 1546 139 
Sum of squares 
4775502 380062 6518 190817 161548 2327 
 
---

Perform an appropriate test to determine whether the investigation provides evidence that the drug is effective in reducing the mean systolic blood pressure.  Determine a 95% confidence interval for the mean change in systolic blood pressure. (10) 
 
Investigate whether the drug is equally effective in reducing diastolic blood pressure. (5) 
 
Make a scatter plot which shows the relation between the change in diastolic blood pressure and the change in systolic blood pressure.  What can be deduced from the scatter plot about the size of the change in diastolic blood pressure compared to the size of the change in systolic blood pressure?  (No detailed calculations are required.) (5) 

--- 

A two-sample t-test would not be appropriate because of the correclation.Paired comparisons
can be examined for systolic and for diastolic by examining the two sets of differences,
that are given. Tn each case a one-trail test sets of difference,against a N.H. that the
true difference= 284
15 = 18:93
Estimated variance =
1
14
(6518 ¡
2842
15
) = 81:495
t(14) =
18:93 ¡ 0
p
81:495=15
= 18:93=2:33 = 8:12

---

    * very strong evidence against the NH; hence very strong evidence in favor of the drug being
effective.
* A 95\% confidence interval for the true mean change is 18:93§t14;5% £2:33 or 18:93§2:145£
2:33 which is 18:93 § 5:00; i:e: 13:93 to 23:93:
Diastolic Mean difference=139/15=9.27
s2 =
1
14
(2327 ¡
1392
15
) = 74:210 t(14) =
9:27 ¡ 0
p
74:21=15
= 9:27=2:22 = 4:17

---

* The 95\% confidence interval is 9:27 § 2:145 £ 2:22 = 9:27 § 4:76 which is 4.51 to 14.03
* Again there is very strong evidence of a real difference, ie that the drug is effective, but the
reduction in diastolic pressure is less than in systolic.
* Generally the two pressures decrease together in the same patient, and roughly speaking
the diastolic reduction is about 2/3 as much as the systolic reduction: the slope of a fitted line
would be about +2/3.






