---
title: "Statistics with R"
subtitle: "R for Actuarial Students"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---

```{r}

#library(xaringan)
```

.
The tensile strength of a synthetic fibre used to make cloth for men's shirts is of
interest to a manufacturer. It is suspected that the strength is affected by the
percentage of cotton in the fibre. Random samples of material with cotton percentage
15, 0, 5, 0 and 5 were taken and five pieces from each material were strength
tested. The recorded strengths are shown below.
15%
7
7
15
11
9
(i)
0%
14
18
17
16
18
5%
15
18
0
18
19
0%
1
17
1
18
18
5%
7
10
11
15
11

---

Complete the analysis of variance table below and state your conclusion about
the effect of the percentage of cotton on the strength of the material.
One-way ANOVA:
Source
Factor
Error
Total
DF
*
*
*
15%, 0%, 5%, 0%, 5%
SS
6.64
*
404.64
MS
65.66
*
F
*

---

(ii)
A standardised residual can be defined as a residual divided by its standard error. Using this definition, the standardised residuals are as shown in the table below. Construct a plot of the standardised residuals versus fitted values, and comment on the assumptions underlying the analysis of variance.

\begin{tabular}{c|c|c|c|c|}
15\%	&	20\%	&	25\%	&	30\%	&	35\%	\\
–1.17	&	–1.09	&	–1.26	&	–1.43	&	–1.59	\\
–1.17	&	0.59	&	0	&	0.67	&	–0.34	\\
2.18	&	0.17	&	0.84	&	–1.43	&	0.08	\\
0.5	&	–0.25	&	0	&	1.09	&	1.76	\\
–0.34	&	0.59	&	0.42	&	1.09	&	0.08	\\
\end{tabular}




---

[(a)]
* The analysis of variance table is as follows. Entries in italics are given in the question. The others need to be calculated.


\begin{tabular}{c|c|c|c|c|}
SOURCE	&	DF	&	SS	&	MS	&	F value	\\
Percentages	&	4	&	262.64	&	65.66	&	9.25	\\
Residual	&	20	&	142	&	7.1	&		\\
TOTAL	&	24	&	404.64	&		&		\\
\end{tabular}


 Compare F4,20

Upper critical points of F4,20 are as follows:
5%
1%
0.1%
2.87
4.43
7.10
The F value for percentages is very highly significant; we have very strong evidence that not all the percentages of cotton are the same in terms of mean tensile strength of the synthetic fibre.
* The fitted values are simply the sample means for the different percentages of cotton: (15\%) 9.8; (20\%) 16.6; (25\%) 18.0; (30\%) 15.4; (35\%) 10.8. The graph suggests that where the mean is lower the variance tends to be slightly higher. The analysis is based on a model in which the residual term has constant variance, but apparent departures from this are not great and there is no reason to doubt the results seriously.
Scatterplot of standardised residuals against fitted values
Standardised residuals
Note. Some points on this graph represent two coincident values.
Note also the "false origin" on the fitted values axis.
%%55

\newpage


(7)
(iii) Use the estimate of the error variance to calculate 95\% confidence intervals for
the mean strength at percentage levels 0, 5 and 0. Present your results
graphically. What would you recommend as the percentage of cotton required
to produce maximum strength?
(5)
(iv) If there were resources to carry out a few more strength tests, describe briefly
what you would do.
()


--- 

* A 95\% confidence interval for an individual mean is given by ˆ2.0865/xσ± where 2.086 is the double-tailed 5\% point of t20.
* Further, , the residual mean square in the above analysis of variance. 
* Thus the interval for 20\% cotton is given by 2ˆ7.10σ=16.62.0867.105/±, i.e. it is (14.1, 19.1).
* Similarly, for 25\% the interval is (15.5, 20.5) and for 30\% it is (12.9, 17.9).
30%
25%
20%
20.0
16.0
12.0
Strength

---

On this evidence, 25% cotton should be used.
(iv) It is worth exploring just below 25%, and perhaps just above. Depending on how much work can be done, it may be possible to search for a maximum in this region.
 
 
 
