---
title: "Statistics with R"
subtitle: "R for Actuarial Students"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---

```{r}

#library(xaringan)
```

 
In a pilot study of anaesthesia in cardiac surgery twenty two patients were randomly assigned to three treatment groups. The table shows the red cell folate levels in the three groups after 24 hours of treatment.
Group A (n = 8)
Group B ( n = 9 )
Group C ( n = 5 ) 243 206 241 251 210 258 275 226 270 291 249 923 347 255 328 354 273 380 285 392 295 309 Sum 2533 2308 2020 Sum of squares 826145 602898 1157058
(i) Make an informative plot of the data. One of the data points seems to be unusual compared with the rest. State which one it is and why you regard it as unusual.




---



 
 
(ii) A one-way analysis of all the data performed by a computer package is summarised in the analysis of variance table below. Some values have been left out of the table. Complete the table and state the conclusions that you feel are justified by this analysis.
Source of variation Sum of squares
Degrees of freedom
Mean square
Variance ratio Between treatments * 2 * * Residual * 19 19797 Total 446405 21

---


 
 
(iii) After some discussion with the surgical team who conducted the study you decide to leave out the observation which is unusual because it is not possible to determine whether it is a genuine observation or a mistake in recording the data. Re-analyse the data and draw up an analysis of variance table similar to the one above. State the conclusions which are justified by your second analysis.
(iv) How would you explain any difference between your conclusions from the two analyses?


---



*  A dot - plot for each set of data, on the same scale, is useful.
* 923 for C seems highly unlikely. This level may be physically impossible, to
judge from all the other observations. Or it may be a recording error for 293
(or even 329).
*  Residual S.S. = 19 £ 19797 = 376143; hence treatment S.S. = 70262 and
M.S. = 35131. The variance ratio is then 35131
19797 = 1:77.
The analysis, by itself, suggests that there are no significant treatment differences,
and also that the standard deviation of an observation is very large
(
p
19797 = 140:7).
* Revised sums and S.S. are:
A B C TOTAL
Sum 2533 2308 1097 5938
n 8 9 4 21
Sum of squares 826145 602898 305129 1734172
Treatments SS = 25332
8 + 23082
9 + 10972
4 ¡ 59382
21 = 1694737¡1679040 = 15697.
25
and Total SS = 1734172 ¡ 59382=21 = 55132.
Source of variation DF Sum of Squares M:S:
Treatments 2 15697 7849 F(2;18) = 3:58¤
Residual 18 39435 2191
TOTAL 20 55132
F is just significant at 5%. The estimated variance of an observation is 2191,
S.D. = 46.8. Means are: A, 316.6; B, 256.4; C, 274.3. Var[¯xA ¡ ¯xB] =
s2( 1
8 + 1
9 ) = 517:32, S.D. = 22.7, t(18) = 60:2
22:7 = 2:65¤, so A and B appear
to differ. Var[¯xA ¡ ¯xC] = s2( 1
8 + 1
4 ) = 821:63, S.D. = 28.7, t(18) = 42:3
28:7 , not
significant. A and C do not differ; nor will B and C.
* The one doubtful observation greatly increased the variance estimate.

















---




 
 
4. Silicon chip manufacture involves a complex process in which layers are deposited on a wafer of silicon by vapour deposition at high temperatures. An electronics engineering team investigated the effect of deposition time and deposition temperature on the thickness of a particular layer. They particularly wanted to find out whether either factor alone could be used to control the thickness of the layer. They used two settings of deposition time  (Low and High relative to currently used time) and two temperatures (1210°C and 1240°C). Measurements of the thickness of the layer were made on each of five silicon wafers produced under each set of conditions. The measurements are given in the table below.
Thickness of layer (Ëm)
Deposition Time High Low
Deposition
1210 14.90,  14.69,  14.52, 15.14,  14.63.
13.78,  14.18,  13.58, 13.58,  13.81.
Temperature
1240 14.49,  14.33,  13.94, 14.31,  14.18.
14.27,  14.37,  14.16, 14.03,  14.20.
The sum of the 20 measurements is 285.09 and the corresponding sum of squares is 4067.00.
(i) Perform an analysis of variance, including tests for the effects of time and temperature and the interaction between time and temperature.



---


 
 
(ii) Produce a diagram of means and their standard errors which makes clear the nature of any interaction that there may be between time and temperature.
(iii) Write a short report (4 or 5 informative sentences) which explains the findings of your analysis in non-technical language for the team who carried out the investigation.

---

4. 2 £ 2 factorial experiment in 5 replicates, completely randomized.
TOTALS.
Time: H L
1210 73:88 68:93 : 142:81
1240 71:25 71:03 : 142:28
145:13 139:96 285:09

*  Correction term G2=N = 285:092=20 = 4063:8154.
S.S. for Times = 1
10(145:132 + 139:962) \;-\;G2
N = 1:33645
S.S. for Temperatures = 1
10(142:812 + 142:282) \;-\;G2
N = 0:01405
S.S. for all “treatments” = 1
5(73:882+68:932+71:252+71:032)¡G2
N = 2:46914.
* Corrected total S.S. = 4067:00 \;-\;4063:8154 = 3:1846.

\begin{verbatim}
Analysis of Variance.
D:F: S:S: M:S:
Temperatures 1 0:01405 0:0141
Times 1 1:33645 1:3365
Interaction 1 1:11864 1:1186 F(1;16) = 25:03¤¤¤
3 2:46914
Residual 16 0:71546 0:0447 = s2:
TOTAL 19 3:18460    
---

Since there is a very strong interaction of time with temperature, main effects
should not be quoted.
*  Means are:
Time: H L
Temperature 1210 14:78 14:79
1240 14:25 14:21

    * A graph shows the results clearly:
* The standard error of a single mean is
p
s2=5 = 0:095. * Hence at 12400 C,
time has no effect, while at 12100 C time H gives a thicker layer.


*  Report should make the point that neither time nor temperature alone
determines the thickness of the layer; also for a thicker layer we should
use the lower temperature and longer time, while the lower temperature
and shorter time gives a relatively thin layer. At the higher temperature,
with either time, the thickness of the layer is between these other two, and
apparently not affected by time.

