---
title: "Statistics with R"
subtitle: "R for Actuarial Students"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---

```{r}

#library(xaringan)
```

 
 
6. A health questionnaire was administered to people in five areas of a country, the selection being made randomly within areas. One question asked the respondent to rate their own health as "good", "fair" or "poor". The results are summarised in the table below.


---
Area	Good Fair Poor Total
Ruthven  459  178  43  680
Mossmont  926  506 103 1535
Windgyle  954  442  78 1474
Dundonan  985  507  85 1 577
Ainster  365  176  35  576
Total 3689 1809 344 5842

Area	|Good | Fair | Poor | Total
Ruthven  |  459  |  178  |  43  |  680
Mossmont  |  926  |  506 | 103 | 1535
Windgyle  |  954  |  442  |  78 | 1474
Dundonan  |  985  |  507  |  85 | 1 | 577
Ainster  |  365  |  176  |  35  |  576
Total | 3689 | 1809 | 344 | 5842


c("Area", "Ruthven", "Mossmont", "Windgyle", "Dundonan", "Ainster", 
"Total")

c("Good", "459", "926", "954", "985", "365", "3689")

c("Fair", "178", "506", "442", "507", "176", "1809")

c("Poor", "43", "103", "78", "85", "35", "344")

c("Total", "680", "1535", "1474", "1577", "576", "5842")

---

(i) Carry out an appropriate statistical test of whether there are differences between perception of health in different areas and investigate the nature of these differences.



---



 
 
(ii) Do you feel that the survey will provide an accurate comparison of health status between the areas? Suggest an alternative way of measuring health status, stating any advantages and disadvantages compared to the survey described here.

\end{tabular}
---


*  Since we have a table of frequencies in various categories, an appropriate Null
Hypothesis is that the ratio Good:Fair:Poor is the same in each area. A Â2
(8)
test is suitable. “Expected” frequencies are calculated from margin totals as
usual, e.g. Ruthven / Good is 680£3689
5842 = 429:39.
OBS(EXP) Good Fair Poor
Area R 459(429:39) 178(210:56) 43(40:04) : 680
M 926(969:29) 506(475:32) 103(90:39) : 1535
W 954(930:77) 442(456:43) 78(86:79) : 1474
D 985(995:82) 507(488:32) 85(92:86) : 1577
A 365(363:72) 176(178:36) 35(33:92) : 576
3689 1809 344 5842
23
(Rounding expected frequencies is to the nearest 0.01).
Â2
(8) =
P (0¡E)2
\[E = 2:04185 + 1:93340 + 0:57977 + 0:11756 + 0:00450 + 5:03492
+1:98027 + 0:45620 + 0:71458 + 0:03123 + 0:21882 + 1:75918
+0:89024 + 0:66530 + 0:03439 = 16:46¤:\]

---

This indicates that there are departures from a constant ratio in some areas.
Comparing observed and corresponding expected frequencies shows that

* Ruthven has more ‘Good’ and less ‘Fair’ than expected; 
* Mossmont has less ‘Good’ and more ‘Fair’ or ‘Poor’; 
* Windgyle has more ‘Good’ and less ‘Fair’ or ‘Poor’; 
* Dundonan has more ‘Fair’ and less ‘Good’ or ‘Poor’.

---

*  Since respondents rate their own health this is very subjective and unlikely
to produce the same ratings for the same condition in different people or
areas. Also we obtain relatively little information per person and so require
a large number of observations.

* Actual measurements on a smaller number of people could provide data
on blood pressure, cholesterol, weight and many other objective ways of
assessing health, as well as observing the presence or absence of infections,
and the general environmental conditions such as air quality.



