---
title: "Statistics with R"
subtitle: "R for Actuarial Students"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---

```{r}

#library(xaringan)
```

 
#### Part 1

Explain what is meant by a factorial experimental design and state what advantages such a design has over a number of separate single factor experiments.


---

The Journal of Applied Ecology for 1997 reports the results of a study of the feeding behaviour of goats, red deer and South American camelids on three different mixtures of Scottish plants.

    *  A group of fifteen  of each type of animal was randomly divided into groups of five.
    * One group of each type of animal was then allocated to feed on  a plot of land where one of the three plant mixtures was growing. 
    * The three plant mixtures were:sown grasses, natural grasses, heathers. 

---
 
 The mean organic matter intake of each group of animals (kg per day) is given in the table below.




\begin{tabular}{|c|c|c|c|}
& Goats&Red Deer&Camelids  
Sown grasses & 0.907 & 2.033 & 1.137 \\
Natural grasses & 1.348 & 2.437 & 1.973\\ 
Heathers & 0.646 & 1.888& 0.970\\
\end{tabular}

---

The total of the intake measurements  for all 45 animals was 66.689 and the sum of the squares of the intake values for all 45 animals was 114.85.
(ii) Carry out an analysis of variance table to analyse the effects of animal types, plant mixtures and any interaction between these factors.
(iii) Construct a suitable graphical display to illustrate the presence or absence of interaction.


---

8.(i)


    * The treatment combinations used in a factorial design are made up of all possible combinations
of levels, or amounts, of several factors that may affect the response being measured. * For example,
15
an industrial process may depend on the time for which it runs, T, and the temperature at which it
is operated, U. * If several values of T and of U are used, say T1; T2; T3; T4 and U1;U2;U3 a factorial
design requires all twelve combinations T1U1 to T4U3 to be used, usually in two or more complete
replicates.
* The response to one factor may take a different pattern at different levels of the other: e.g. at
U1 there may be a linear change from T1 to T4 whereas it is quadratic at U2, and irregular at U3.
* This is interaction between T and U and is not discovered unless a factorial design is used.
* 
Totals of responses are required for analysis, i.e. means $\times 5$.



\begin{tabular}{|c|c|c|c|}
& Goats&Red Deer&Camelids  
Sown grasses&4.535&10.165&5.685\\
Natural grasses&6.740&12.185&9.865\\
Heathers&3.230&9.440&4.850\\
\end{tabular}



Grand total G=66.695.%% [MISPRINT ON PAPER]

---

(ii)Correction term

\[ \frac{G^2}{N} = \frac{66.695^2}{45} = 98.8494.\]

\[Total S.S.= 114.85 - \frac{G^2}{N} = 16.0006.\]

--- 

Total for Animals are 14.505, 31.790, 20.400; for plants 20.385, 28.790, 17.520.



\item
\[S.S. Animals= \frac{1}{15} (14.505^2 + 31.790^2 + 20.400^2) - \frac{G^2}{N} = 10.2945.
\]
\item
\[S.S. Plants= \frac{1}{15} (20.385^2 + 28.790^2 + 17.520^2) - \frac{G^2}{N}= 4.5748.
\]
* S.S. Animals+S.S. plants +S.S. Interaction
\[= \frac{1}{5}(4.535^2 + \ldots + 4.850^2) - \frac{G^2}{N} = 15.2509.
\]

---

Hence the Analysis of Variance.


\begin{tabular}{|c|c|c|c|c|c|}
SOURCE OF&D.F.&SUM OF&MEAN& VARIANCE & \\
VARIATION    & &SQUARES&SQUARE& RATIO &
Animal Types & 2 &10.2945 &5.1473& & 
Plant Types  & 2 &4.5748 &2.2874 & & 
Interaction  & 4 &0.3816 &0.0954&4.58 &F(4;36) 
Residual     &36 &0.7497 &0.02083 &  & 
TOTAL        &44 &16.0006 & & &  
\end{tabular}


---

* There is strong evidence of interaction between Animals and Plants. Graphs of the means for
the nine combinations are required.
* In the presence of interaction, the main effects of the factors have little meaning. We may
note that levels for Red Deer are consistently above those for Camelids, which are also above those
for Goats.
* 
Camelids show a different pattern from Goats and Red Deer, in that their intake from natural
grasses is relatively higher than from sown grass or heathers; the figure 1.973 is the odd one out
in the table of means.

