---
title: "Statistics with R"
subtitle: "R for Actuarial Students"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---



Higher Certificate, Paper III, 2004.  Question 5 
 

5. The table shows, for South Africa, details of the numbers of road traffic collisions and casualties associated with them, in four years. 
 
(i) Examine the changes over time, considering in particular whether or not accidents are becoming less serious.  Support your answer by any diagrams and calculations you think are appropriate. 
 
(ii) What other background information might be useful in interpreting the figures in this table, and why? 
 
---

 Numbers  1994 1995 1996 1997      Collisions        Fatal     8140     8335     7850     7790    Major   22594   23988   22707   23059    Minor   60199   61716   54190   57391    No injury 377064 406194 436027 417748 Total 467997 500233 520774 505988      Casualties        Killed     9981   10256     9848     9691    Seriously injured   36548   39780   38473   39302    Slightly injured   91887   96689   86728   91760 Total 138416 146725 135049 140753 
       Source: Statistics South Africa. 
---
 
(i) The total number of collisions rose steadily for the first three years and then fell in 1997.  Total casualties rose in 1995, then dropped in 1996 and then rose again in 1997.  Percentage changes from one year to the next were as follows. 
  1994 to 1995 1995 to 1996 1996 to 1997 Total collisions +6.9 +4.1 –2.8 Total casualties +6.0 –8.0 +4.2 

* To consider seriousness of collisions, we might combine "fatal" and "major":- 
  1994 1995 1996 1997 Number 30734 32323 30557 30849 % of total collisions 6.6 6.5 5.9 6.1 
 The actual numbers were very similar except for the increase in 1995, but in the last two years they were a smaller proportion of the total. 
 
 
---

* Similarly we might combine "killed" and "seriously injured", noting that the number of fatal casualties was least in 1997 whereas the number of seriously injured was least in 1994:- 
  1994 1995 1996 1997 Number 46529 50036 48321 48993 % of total casualties 33.6 34.1 35.8 34.8 


The actual numbers increased in 1995 but then steadied off;  however, the percentages of the total increased for three years before falling slightly. 
 
* Useful diagrams would be component bar charts showing the annual totals of collisions and of casualties, with the components in each category (fatal etc, or killed etc) shown in different shading or colouring.  Because annual changes are fairly small relative to total sizes, these diagrams will not show obvious or clear trends. 
 
---
 
 
(ii) Examples of useful background information are 
*  occupancy of vehicles involved – e.g. driver only, few passengers, many passengers as in coaches 
*  type of vehicle – e.g. heavy lorry, car or other small vehicle (some collisions, e.g. between a lorry and a small car, seem more likely to cause fatalities) 
*  traffic density at the time 
*  numbers of registered vehicles in the year, indicating general level of road use / congestion 
*  mileage travelled by drivers involved 
*  ages of vehicles 
*  ages of drivers and length of experience*  roadworks or other local hazards. 
 
---