---
title: "Statistics with R"
subtitle: "R for Actuarial Students"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---

```{r}

#library(xaringan)
```

---
For a study into the density of population around a large city, a random sample of 10
residential areas was selected, and for each area the distance from the city centre and
the population density in hundreds per square kilometre were recorded. The following
table shows the data and also the log of each measurement.
distance, x (km) population density, y
0.4
149
1.0
141
.1
10
4.5
46
4.7
7
6.5
40
7.

8.
15
9.7
7
11.7
5
(i)
log x
–0.916
0.000
1.11
1.504
1.548
1.87
1.988
.104
.7
.460
log y
5.004
4.949
4.65
.89
4.77
.689
.15
.708
1.946
1.609

---

By plotting three separate graphs, decide which of the following regressions is
best represented by a straight line.
(a)
y on x
(b) y on log x
(c) log y on x
(7)
(ii) On the basis of the regression results on the next page, which regression do
you consider to be best? Justify your answer by reference to the diagnostic
criteria given in the output and relating these to your plots in (i). Would you
consider regressing log y on log x? If not, why not?
(5)


---
[(i)]
* There is some curvature in all these plots; log y on x is slightly "straighter" than y on x. Using log x looks worst. So use log y on x.
*  (c) has the highest R2 – though all are good.
(c) also has the highest t values for the coefficients – though again all are good.
(c) also has the lowest residual variance relative to the mean response.
(c) is the only one without a "large" residual.
(c) appeared (marginally) the best plot.
It does not seem sensible to regress log y on log x; it looks as if this would increase the curvature.

---

(iii) For the model you consider to be best in (ii), obtain an expression for y in
terms of x.
()
(iv) Using your chosen model, estimate the density of the population at a distance
of 5 km from the city centre.
()
(v) State any reservations you have about using the model to predict population
density.
()
The regression results for this question are on the next page

---

* Using (c), we have log y = 5.41 – 0.322x, so
()5.410.3220.322exp5.410.322223.63xxyxee−−=−== .
*  From the expression in part (iii), inserting x = 5, 1.61223.63ye−= = 44.7. This is in hundreds per square kilometre. So the estimate is 4470 per square kilometre.


---

* Prediction within the range of the data may be adequate, except perhaps near the upper end because of the tendency for curvature there. Extrapolation to values of x outside the data will, for similar reasons, be unreliable, and the linear model is likely to underestimate density. Where is the next city or town centre? Interaction with that is very likely unless it is a long distance away. There may also be directional effects, i.e. densities changing more or less slowly according to the direction from the centre.
 
 

---

Regression results for question 7
Regression Analysis: y versus x
The regression equation is y = 140 - 14.0x
Predictor
Constant
x T
1.56
-8.9
Coef
19.70
-1.958
S = 18.84
SE Coef
11.1
1.66
R-Sq = 89.8%
P
0.000
0.000
R-Sq(adj) = 88.5%

---

Observation 10 has an unusually large positive residual
Regression Analysis: y versus logx
The regression equation is y = 17 - 48.0logx
Predictor
Constant
logx
Coef
16.990
-47.980
S = 17.049
SE Coef
9.147
5.9
R-Sq = 91.1%
T
1.88
-9.07
P
0.000
0.000
R-Sq(adj) = 90.0%
Observation 1 has an unusually large negative residual
Regression Analysis: logy versus x

---

The regression equation is logy = 5.41 - 0.x
Predictor
Constant
x
Coef
5.41
-0.157
S = 0.66544
SE Coef
0.161
0.045
T
.40
-1.6
R-Sq = 95.6%
P
0.000
0.000
R-Sq(adj) = 95.1%

---
 
 
