---
title: "Statistics with R"
subtitle: "R for Actuarial Students"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---

```{r}

#library(xaringan)
```

 
2. The results of two surveys of public opinion relating to genetically engineered food were published in a popular science magazine.  The magazine article began by claiming that opposition to genetically engineered food was growing in Britain and it also contained a quote from the director of Genewatch who was reported to have said "Opinion has hardened against genetic engineering quite significantly". 
 
--- 
 
The article contained a table which summarised the results of two opinion polls, the first conducted in 1996 and the second in 1998.  Both polls were carried out by a reputable market research organisation which asked 1000 adults the same question on both occasions.  You may assume that the polls were properly conducted and the people questioned on each occasion were randomly sampled from the population.  Note that the people questioned in 1996 were not the same as those questioned in 1998. 
 
--- 
 
The table contained in the article is given below. 
 
What do you think of genetically engineered food?  1996 (\%) 1998 (\%) Support it to a great extent 6.0 6.0 Support it slightly 25.0 16.0 Neither support nor oppose it 16.0 15.0 Oppose it slightly 24.0 21.0 Oppose it to a great extent 27.0 37.0 Don't know 2.0 5.0 
 
 


---


[(a)]
* A Â2-test has to uses exact frequencies, not percentages. It can test the Null Hypothesis
that the ratios of frequencies between the six categories were the same in both years. On-this
NH, expected frequencies area given in brackets:


\begin{tabular}{|c|c|c|c|c|c|c|c}
Category & 1 & 2 & 3 & 4 & 5 & 6 \\
1996 & 60(60) & 250(205)  &160(155)& 240(225) & 270(320)& 20(35)& 1000
1998 & 60(60) & 160(205) & 150(155) & 210(225) & 370(320)&  50(35) & 1000
& 120&  410 & 310&  450&  640 & 70&  2000
\end{tabular}



$$\chi^2_{(5)} &=& 0 +  \frac{(250-205)^2}{205}  + \frac{(160-155)^2}{155} + \frac{(160-155)^2}{155}  +\frac{(270-320)^2}{320} + \frac{(20-35)^2}{35} + \\
& & 0 + \frac{(160-205)^2}{205} + \frac{(150-155)^2}{155}  + \frac{(160-155)^2}{155}+  \frac{(370-320)^2}{320} +
 \frac{(50-35)2}{35} \\
&=& 48.56\\
$$

There is very strong evidence against the NH.


* Looking at the percentages through the categories, the numbers opposing have increased over
the period, ”slight support ”having dropped substantially and ” great opposition” increased.
On the face of it, the magazine was justified.
* But much more information could be extracted by attaching a scoring scale, such as ¡2; ¡1; 0;
1; 2 to the first five categories, omitting the ”don’t knows” and looking at scores, or some others
suitable statistic. 
* If the linear scale is (approximately)valid, this will extract more information
than simple categorization. 
* But it may be unwise to assume linearity, and also not easy to
13
decide how to score very strong views.

*  n1 = n2 = 1000; 
*   p1 = 0.51; p2 = 0.58; 
*   p2 ¡ p1 = 0:07
*  \[
V [p2 - p1] =
\sqrt{\frac{0:58 \times 0:42}{1000}
+
\frac{0:51 \times 0:49}{1000}
} = 0:0222\]; 
*  Standard Error: $SE = 0:0222$




 
 
Given the above information carry out a chi-squared test to determine whether the claims made by the magazine are supported by the poll results.  Comment on the limitations of this test.
 


---


 
 
Determine a 95\% confidence interval for the change between 1996 and 1998 in the proportion of the population who oppose genetically engineered food slightly or to a great extent. (8) 

---
* 95\% confidence interval for true value of p2¡p1 is 0:07§1:96£0:0222 = 0:07§0:0435 or 0:026 to 0:114
i.e. with 95\% probability the difference lies between 2:6\% and 11:4\%. The evidence is that
there has been a shift against, of this extent.


