---
title: "Statistics with R"
subtitle: "R for Actuarial Students"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---

```{r}

#library(xaringan)
```



8.
The table below shows, for graduate entrants to an organisation during the last five
years, the numbers of males and the numbers of females with each class of degree.
You may treat the data as if they were a random sample from a large population.

---

\begin{tabular}{|c|c|c|}
Class of degree	&	Male	&	Female	
1st	&	18	&	17	
2nd	&	90	&	50	
3rd	&	12	&	18	
Pass	&	61	&	32	
\end{tabular}

(i) Test whether there is an association between sex and class of degree. Write a
short report to the personnel manager of the organisation describing your
findings in non-technical language.


(ii) The national percentage of all graduates obtaining first class degrees during the
last five years was 8.3. Assuming the number of graduate entrants having first
class degrees follows a binomial distribution, investigate whether the overall
proportion of graduates with first class degrees recruited by this organisation in
this period is more than the average. Why might the assumption of a binomial
distribution not be strictly valid?

---

(iii) Use the summary data from the last five years to investigate whether the
population proportion of graduate entrants to this organisation who have
second class degrees is the same for males as for females.
(5)

%%%%%%
[(a)]
    *  
(i) Observed and expected (on the null hypothesis of no association between class of degree and sex) frequencies, and the individual contributions of each cell to the X 2 statistic, are as follows. 
 

\begin{tabular}{|c|c|c|c|} 
Class of degree	&	Male	&	Female	&	Total	
1st	&	18	&	17	&	35	
2nd	&	90	&	50	&	140	
3rd	&	12	&	18	&	30	
Pass	&	61	&	32	&	93	
	&	181	&	117	&	298	
\end{tabular}



\begin{tabular}{|c|c|c|c|} 							
Class of degree	&	Male	&	Female	&	Total	
1st	&	21.26	&	13.74	&	35	
2nd	&	85.03	&	54.97	&	140	
3rd	&	18.22	&	11.78	&	30	
Pass	&	56.49	&	36.51	&	93	
	&	181	&	117	&	298	
\end{tabular}

---

\begin{tabular}{|c|c|c|c|} 							
Class of degree	&	Male	&	Female	&	Sum	
1st	&	0.50	&	0.77	&		
2nd	&	0.29	&	0.45	&		
3rd	&	2.12	&	3.29	&		
Pass	&	0.36	&	0.56	&		
	&		&		&	8.34	
\end{tabular}
 
 
---
 
%18 17   21.26 13.74   0.4999 0.7735 90 50   85.03 54.97   0.2905 0.4494 12 18   18.22 11.78   2.1234 3.2842 61 32   56.49 36.51   0.3601 0.5571 
*  The test statistic is () 2 2 OEX E − =∑ = 8.34.  

* For determining the criticcal value, the degrees of freedom is $(r-1)\times (c-1)$ = $(4-1) \times (2-1)  = 3$.
Therefore we refer the test statistic to $\chi^2_{3}$ . 


---

* The upper 5\% point is 7.815, so the result is significant at the 5\% level.  
* We have evidence to reject the null hypothesis  –  it seems there is a relation. 
 * The individual contributions to $\chi^2$ show that the main contributions come from the cells for the 3rd class degree (the third row of the table), where we find fewer males and more females than would be expected.  
 * This is also the case for 1st class degrees, balanced by the opposite being true for 2nd class and Pass degrees, but these cells do not make such a marked contribution.  These comments would be the substance of the report. 
 
--- 
 
*  We have $\displaystyle \hat{p} = \frac{35}{298} = 0.117 }$for this organisation.  

    * The national population value of p is 0.083. 
    * We want to test the null hypothesis that the proportion in this organisation is the same as the national value, against the alternative that this organisation's value is higher. 
    * With a sample of size as large as 298, even with p as small as 0.083, a Normal approximation should be adequate.
    * So the test statistic (without continuity correction) is 
 
() ( )( ) ˆ 0.117 0.083 0.034 2.13 0.0161 / 0.083 0.917 /298 pp p p n −− = = = − , 
 
which is referred to $N(0, 1)$ in a one-sided interpretation.
* The result is significant at the 5\% level (critical point 1.645) and approaching significance at the 1\% level (critical point 2.326).  
* There is considerable evidence that this organisation's proportion is higher than the national value. 

 
The proportions of males and females with first class degrees are likely to be different, so to pool all the data into a single binomial distribution and test is not strictly correct. 
 
---

#### Part (c)
 
 
*  For this organisation, ˆ ˆ 90/181 0.497, 50/117 0.427 MF pp = = = =.  The estimated variance of ˆˆ MFp p− is given by 
 0.497 0.503 0.427 0.573 0.003472 181 117 ×× += . 
 
* So the (Normal approximation) test statistic for testing the null hypothesis that the true values of $p_M$ and $p_F$ are equal is 
 0.497 0.427( 0) 1.19 0.003472 −− = . 
 
* Referring this to N(0, 1), the result is not significant  –  there is no evidence to suggest that pM and pF are not equal. 
 
---
 
* An alternative method for this part is a $2 × 2$ contingency table.  The observed frequencies are 
 
 2nd class Other Male 90 91 Female 50 67 
 
and the expected frequencies if there is no association are 
 
 2nd class Other Male 85.034 95.966 Female 54.966 62.034 
*  These give $\chi^2$ test statistic 1.39 (without use of Yates' correction) which, on reference to 2 1χ , is not significant. 


 
