---
title: "Statistics with R"
subtitle: "R for Actuarial Students"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---

```{r}

#library(xaringan)
```

 
5. You have been asked by a horticulturalist at a research station to advise on the design of an experiment on the growth of tomatoes which is to be undertaken in a glasshouse environment. The experiment is to compare the effects on mean fruit yield of four different nutrient solutions. Plants will be grown in commercial “grow-bags”, which are rectangular plastic bags containing a standard growing medium. There will be four plants to a bag and there will be the same number of plants per nutrient solution. It is not possible to provide different nutrient solutions to plants which are in the same bag. There is enough space in the glasshouse for two  rows each containing 32 full grow bags, laid side by side.

(i) The horticulturalist has heard of completely randomised and randomised blocks designs and asks for your advice on which one to use. What questions would you ask the horticulturalist before making a recommendation to him?

---
 
(ii) Explain what constitutes an experimental unit in this experiment and what outcome variable  would form the basis of your analysis.

---
 
(iii) Indicate, for both designs, how the nutrient solutions would be allocated to plants.
(iv) Give a breakdown of the sources of variation and the degrees of freedom for the analysis of both designs.

---


* We need to find out whether there are systematic trends along the rows, and / or whether one row is likely to do better than the other.

* We also want to know whether all the grow-bags came from the same source, contain the same compost mixture, are the same size, have equally good
drainage, the same thickness of wall so that temperature is likely to be the same.
* Reasons for blocking would be: difference between rows, trend along rows, different sorts of bag.


*  The experimental unit is a bag of 4 plants. We would analyse the total (or mean) yield of plants per bag. If any plants died, we would need to adjust for this, so it should be recorded.

*  If there is no known or suspected systematic variation revealed in the answers to (i), a completely randomized design may be used, with a fully random
choice of 16 bags for each of the four nutrient solutions. 

---

* This could be achieved by using a random number table, reading digits in pairs, discarding
pairs 00, 65 - 99, taking the first 16 positions for treatment A, the next 16 for B, the next 16 for C and the others for D, 01 - 64 represent the two rows with 32 bags in each.

* If the answers to (i) indicate likely differences in the positions, make up 16
blocks each of which is as homogeneous as possible. 

Number the bags 1,2,3,4 in each block and permute these numbers at random to determine the order
in which the 4 nutrients will be allocated to bags.

---

* For the completely randomized design, the analysis is:
Source of Variation D.F.
Nutrients 3
Residual 60
TOTAL 63
Using blocks of 4 in a randomized complete block design gives:
Source of Variation D.F.
Blocks 15
Nutrients 3
Residual 45
TOTAL 63


