---
title: "Probability Distributions with R"
subtitle: "Introduction to R"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
```

```{css, echo=FALSE}
pre {
  background: #ADD8E6;
  max-width: 100%;
  overflow-x: scroll;
}
```
Telephone calls arrive at a switchboard at the rate of 20 per hour.  Assume that the telecentre operators take 4 minutes to deal with a customer query.  
Calculate the probability of :
### Exercises 
1.  3 or more calls arriving in any 4 minute period.
(ii)   No phone calls arriving in a 4 minute period,
(iii)  Exactly one phone call arriving in any 4 minute period,
(iv) (1 Marks) What is the average and standard deviation of the number of phone calls arriving in a 4 minute period.

% (When answering, justify your answer with workings, or by reference to an axiom, theorem or rule.)
%--------------------------------------------------------------%
\subsection*{Part 2C}
(c)Telephone calls coming in to a busy switchboard follow a Poisson distribution with 3 calls expected in a one minute period.  
The switchboard operator can answer at most 3 calls in a one minute period; the fourth and succeeding calls receive a busy signal.
### Exercises 
1.      Find the probability of receiving a busy signal.
(ii)     The switchboard operator leaves the switchboard unattended for 2 minutes.  
(iii)  What is the probability that exactly 1 call will be missed during that 2 minute period?
   
