
Package ‘rockchalk’
November 9, 2018
Type Package
Title Regression Estimation and Presentation
Version 1.8.129
Date 2018-11-09
Maintainer Paul E. Johnson <pauljohn@ku.edu>

#### Description
 A collection of functions for interpretation and presentation of regression analysis. These functions are used
to produce the statistics lectures in <http://pj.freefaculty.org/guides>. Includes regression
diagnostics, regression tables, and plots of interactions and
``moderator'' variables. The emphasis is on ``mean-centered'' and ``residual-centered'' predictors. The vignette 'rockchalk' offers a
fairly comprehensive overview. The vignette 'Rstyle' has advice about coding in R. The package title 'rockchalk' refers to our
school motto, 'Rock Chalk Jayhawk, Go K.U.'.

* License GPL (>= 3.0)
* LazyLoad yes
* Depends R (>= 2.10)
* Imports grDevices, methods, lme4, carData, MASS, kutils
* Suggests tables, Hmisc, car
* RoxygenNote 6.0.1
* NeedsCompilation no
* Author Paul E. Johnson [aut, cre],
* Gabor Grothendieck [ctb]

Repository CRAN
Date/Publication 2018-11-09 21:10:04 UTC
R topics documented:
rockchalk-package . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 3
addLines . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 4
1
2 R topics documented:
centerNumerics . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 6
centralValues . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 7
cheating . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 8
checkIntFormat . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 9
checkPosDef . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 10
combineLevels . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 10
cutByQuantile . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 11
cutBySD . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 12
cutByTable . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 13
cutFancy . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 13
descriptiveTable . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 15
dir.create.unique . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 17
focalVals . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 18
formatSummarizedFactors . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 19
formatSummarizedNumerics . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 20
genCorrelatedData . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 21
genCorrelatedData2 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 22
genCorrelatedData3 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 25
genX . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 29
getAuxRsq . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 30
getDeltaRsquare . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 31
getFocal . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 32
getPartialCor . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 33
getVIF . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 34
gmc . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 35
kurtosis . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 37
lazyCor . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 38
lazyCov . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 39
lmAuxiliary . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 40
magRange . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 40
makeSymmetric . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 41
makeVec . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 42
mcDiagnose . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 43
mcGraph1 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 44
meanCenter . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 46
model.data . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 50
model.data.default . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 51
mvrnorm . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 54
newdata . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 56
outreg . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 63
outreg0 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 68
outreg2HTML . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 72
padW0 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 73
pctable . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 74
perspEmpty . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 77
plot.testSlopes . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 78
plotCurves . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 79
plotFancy . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 84
rockchalk-package 3
plotPlane . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 85
plotSeq . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 89
plotSlopes . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 90
predictCI . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 95
predictOMatic . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 96
print.pctable . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 103
print.summarize . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 104
print.summary.pctable . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 104
rbindFill . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 105
religioncrime . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 106
removeNULL . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 107
residualCenter . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 108
skewness . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 111
standardize . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 112
summarize . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 113
summarizeFactors . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 116
summarizeNumerics . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 118
summary.factor . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 119
summary.pctable . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 120
testSlopes . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 121
vech2Corr . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 123
vech2mat . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 124
waldt . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 125
Index 127
rockchalk-package rockchalk: regression functions

#### Description

Includes an ever-growing collection of functions that assist in the presentation of regression models.
The initial function was outreg, which produces LaTeX tables that summarize one or many
fitted regression models. It also offers plotting conveniences like plotPlane and plotSlopes,
which illustrate some of the variables from a fitted regression model. For a detailed check on multicollinearity,
see mcDiagnose. The user should be aware of this fact: Not all of these functions lead
to models or types of analysis that we endorese. Rather, they all lead to analysis that is endorsed
by some scholars, and we feel it is important to facilitate the comparison of competing methods.
For example, the function standardize will calculate standardized regression coefficients for all
predictors in a regression model’s design matrix in order to replicate results from other statistical
frameworks, no matter how unwise the use of such coefficients might be. The function meanCenter
will allow the user to more selectively choose variables for centering (and possibly standardization)
before they are entered into the design matrix. Because of the importance of interaction variables in
regression analysis, the residualCenter and meanCenter functions are offered. While mean centering
does not actually help with multicollinearity of interactive terms, many scholars have argued
that it does. The meanCenter function can be compared with the "residual centering" of interaction
terms.
4 addLines
Author(s)
Paul E. Johnson <pauljohn@ku.edu>
References
http://pj.freefaculty.org/R
