
vech2Corr Convert the vech (column of strictly lower trianglar values from a matrix)
into a correlation matrix.

#### Description

vech2Corr is a convenience function for creating correlation matrices from a vector of the lower
triangular values. It checks the 
</code></pre>
#### Arguments
 to make sure they are consistent with the requirements
of a correlation matrix. All values must be in [-1, 1], and the number of values specified must be
correct for a lower triangle.

#### Usage
<pre><code>


vech2Corr(vech)

</code></pre>
#### Arguments

vech A vector of values for the strictly lower triangle of a matrix. All values must be
in the [0,1] interval (because they are correlations) and the matrix formed must
be positive definite.

#### Details

Use this in combination with the lazyCov function to convert a vector of standard deviations and
the correlation matrix into a covariance matrix.
Value
A symmetric correlation matrix, with 1’s on the diagonal.
Author(s)
Paul E. Johnson <pauljohn@ku.edu>
See Also
Similar functions exist in many packages, see vec2sm in corpcor, xpnd in MCMCpack
124 vech2mat

#### Examples
```{r}


v <- c(0.1, 0.4, -0.5)
vech2Corr(v)
v <- c(0.1, 0.4, -0.4, 0.4, 0.5, 0.1)
vech2Corr(v)
